name: PR Checklist Completed

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  pr-approval-checklists:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/require-checklist-action@v2
        with:
          requireChecklist: false # If this is true and there are no checklists detected, the action will fail
          issueNumber: ${{ github.event.issue.number }}
