name: PR Checklist Re-run check
on: issue_comment
  pull_request:
    types: [opened, edited]

jobs:
  pr-approval-checklist-refresh-status:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch of PR commented on
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch

      - name: Re-run the build step
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.checks.listSuitesForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "${{ steps.comment-branch.outputs.head_sha }}",
              check_name: "PR Approval Checklist"
            }).forEach(suite => {
              github.rest.checks.rerequestSuite({
              owner: context.repo.owner,
              repo: context.repo.repo,
                check_suite_id: suite.id
              });
            })