name: Add PR Approval Checklist Comment
on:
  pull_request:
    types: [opened]

jobs:
  pr-approval-checklist-add-checklist-comment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "**PR Approval Checklist:**\n\nThe following checkboxes must be checked (or strike-through) before the PR can be merged.  These can be done by the PR submitter, or the approver.\n- [ ] PR description has sufficient detail (why are we doing this? where can more context be found?)\n- [ ] Automated regression tests have been added/updated\n- [ ] Manual testing has been performed on the deployed branch\n- [ ] Design review has been requested ([if appropriate](https://app.getguru.com/card/T9p6gRyc/PR-Review-Guideline-Expectations-Process))\n- [ ] QA review has been requested (if appropriate)\n- [ ] Relevant DRIs have been informed\n\nPlease check each boxes above as it is satisfied."
            })