name: PR Checklist Completed

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  pr-approval-checklists:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch of PR commented on
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch

      - name: Set the PR's latest commit status to "pending"
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: "${{ steps.comment-branch.outputs.head_sha }}",
              context: "PR Approval Checklist",
              state: "pending",
            })

      - name: Analyze comments, see if all checklists are completed
        uses: mheap/require-checklist-action@v2
        with:
          requireChecklist: false # If this is true and there are no checklists detected, the action will fail

      - name: Set the PR's latest commit status as ${{ job.status }}
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: "${{ steps.comment-branch.outputs.head_sha }}",
              state: "${{ job.status }}",
              context: "PR Approval Checklist",
              description: "PR approval checklist: ${{ job.status }}"
            })